server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/flooddb.tail81da12.ts.net.FLOODDB
    username: flood_app
    password: flood_app
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

logging:
  level:
    com.estate.floodzoning: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
